/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2018-2019 Erik Moqvist
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * This file was generated by asn1tools version 0.167.0 Mon Mar 10 19:55:35 2025.
 */

#ifndef OER_H
#define OER_H

#include <stdint.h>
#include <stdbool.h>
#include <unistd.h>

#ifndef ENOMEM
#    define ENOMEM 12
#endif

#ifndef EINVAL
#    define EINVAL 22
#endif

#ifndef EOUTOFDATA
#    define EOUTOFDATA 500
#endif

#ifndef EBADCHOICE
#    define EBADCHOICE 501
#endif

#ifndef EBADLENGTH
#    define EBADLENGTH 502
#endif

#ifndef EBADENUM
#    define EBADENUM 503
#endif

/**
 * Type SignedData in module SendData.
 */
struct oer_send_data_signed_data_t {
    struct {
        uint8_t buf[120];
    } data;
    struct {
        uint8_t buf[32];
    } signer;
    struct {
        uint8_t buf[65];
    } signature;
};

/**
 * Type Content in module SendData.
 */
enum oer_send_data_content_choice_e {
    oer_send_data_content_choice_signedData_e,
    oer_send_data_content_choice_signedCertificateRequest_e
};

struct oer_send_data_content_t {
    enum oer_send_data_content_choice_e choice;
    union {
        struct oer_send_data_signed_data_t signedData;
        struct {
            uint8_t buf[32];
        } signedCertificateRequest;
    } value;
};

/**
 * Type SendData in module SendData.
 */
struct oer_send_data_send_data_t {
    uint8_t protocolVersion;
    struct oer_send_data_content_t content;
};

/**
 * Type Uint8 in module SendData.
 */
struct oer_send_data_uint8_t {
    uint8_t value;
};

/**
 * Encode type SignedData defined in module SendData.
 *
 * @param[out] dst_p Buffer to encode into.
 * @param[in] size Size of dst_p.
 * @param[in] src_p Data to encode.
 *
 * @return Encoded data length or negative error code.
 */
ssize_t oer_send_data_signed_data_encode(
    uint8_t *dst_p,
    size_t size,
    const struct oer_send_data_signed_data_t *src_p);

/**
 * Decode type SignedData defined in module SendData.
 *
 * @param[out] dst_p Decoded data.
 * @param[in] src_p Data to decode.
 * @param[in] size Size of src_p.
 *
 * @return Number of bytes decoded or negative error code.
 */
ssize_t oer_send_data_signed_data_decode(
    struct oer_send_data_signed_data_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Encode type Content defined in module SendData.
 *
 * @param[out] dst_p Buffer to encode into.
 * @param[in] size Size of dst_p.
 * @param[in] src_p Data to encode.
 *
 * @return Encoded data length or negative error code.
 */
ssize_t oer_send_data_content_encode(
    uint8_t *dst_p,
    size_t size,
    const struct oer_send_data_content_t *src_p);

/**
 * Decode type Content defined in module SendData.
 *
 * @param[out] dst_p Decoded data.
 * @param[in] src_p Data to decode.
 * @param[in] size Size of src_p.
 *
 * @return Number of bytes decoded or negative error code.
 */
ssize_t oer_send_data_content_decode(
    struct oer_send_data_content_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Encode type SendData defined in module SendData.
 *
 * @param[out] dst_p Buffer to encode into.
 * @param[in] size Size of dst_p.
 * @param[in] src_p Data to encode.
 *
 * @return Encoded data length or negative error code.
 */
ssize_t oer_send_data_send_data_encode(
    uint8_t *dst_p,
    size_t size,
    const struct oer_send_data_send_data_t *src_p);

/**
 * Decode type SendData defined in module SendData.
 *
 * @param[out] dst_p Decoded data.
 * @param[in] src_p Data to decode.
 * @param[in] size Size of src_p.
 *
 * @return Number of bytes decoded or negative error code.
 */
ssize_t oer_send_data_send_data_decode(
    struct oer_send_data_send_data_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Encode type Uint8 defined in module SendData.
 *
 * @param[out] dst_p Buffer to encode into.
 * @param[in] size Size of dst_p.
 * @param[in] src_p Data to encode.
 *
 * @return Encoded data length or negative error code.
 */
ssize_t oer_send_data_uint8_encode(
    uint8_t *dst_p,
    size_t size,
    const struct oer_send_data_uint8_t *src_p);

/**
 * Decode type Uint8 defined in module SendData.
 *
 * @param[out] dst_p Decoded data.
 * @param[in] src_p Data to decode.
 * @param[in] size Size of src_p.
 *
 * @return Number of bytes decoded or negative error code.
 */
ssize_t oer_send_data_uint8_decode(
    struct oer_send_data_uint8_t *dst_p,
    const uint8_t *src_p,
    size_t size);

#endif
